#!/bin/sh
#                        __ _ _
# __  ___ __  _ __ ___  / _(_) | ___
# \ \/ / '_ \| '__/ _ \| |_| | |/ _ \
#  >  <| |_) | | | (_) |  _| | |  __/
# /_/\_\ .__/|_|  \___/|_| |_|_|\___|
#      |_|
#
# This file runs when a DM logs you into a grapical session
# and is sourced by xinitrc

# Apply .Xresources (not asynchronosly as following commands need it)
[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources ] &&
	xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources

# Scratchpads
$TERMINAL -n dropdown-general -e $SHELL -c "neofetch;$SHELL" &
$TERMINAL -n dropdown-math -f xft:Hack:pixelsize=24 -e qalc -c &

# Set background (using custom script)
setbg

# Blue light filter
redshift &

# Statusbar
# dwmblocks &

# Opacity effects
# picom -b -experimental-backends
picom -b

# Hide mouse cursor when typing
xbanish &

# Flash the focused window
flashfocus &

# Notifications
dunst &

# Set numlock
xdotool key --clearmodifiers Num_Lock &

# Setup extended monitor
xrandr --output HDMI1 --auto --left-of eDP1 &

# Set keyboard settings
# - Toggle layout with Alt+Shift
# - Replace comma with dot on numpad
# - Swap CAPS and ESC keys
setxkbmap -layout at,us \
	-variant nodeadkeys,dvorak \
	-option "grp:alt_shift_toggle" \
	-option "kpdl:dot" \
	-option "caps:swapescape" &

# Setup key bindings for AltGr
xmodmap -e "keycode 28 = t T t T asciitilde"
xmodmap -e "keycode 38 = a A a A braceleft"
xmodmap -e "keycode 39 = s S s S braceright"
xmodmap -e "keycode 40 = d D d D bracketleft"
xmodmap -e "keycode 41 = f F f F bracketright"
xmodmap -e "keycode 42 = g G g G backslash"
xmodmap -e "keycode 56 = b B b B backslash"

# setup lock screen (xautolock will also be called by suspend@USER.service)
xautolock -detectsleep -resetsaver \
	-locker "xsecurelock" -time 10 -notify 5 \
	-notifier "/usr/lib/xsecurelock/until_nonidle /usr/lib/xsecurelock/dimmer" \
	-killer "systemctl suspend" -killtime 50 &

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd &

# Syncthing (for syncing folders with computers/smartphones)
syncthing -no-browser -no-restart -logflags=0 &

# Apply cursor theme (workaround for bug in awesome wm)
xsetroot -cursor_name left_ptr &

# Startup applications
firefox &
$TERMINAL -n ncmpcpp -e $SHELL -c "ncmpcpp" &
