#!/bin/sh
#                        __ _ _
# __  ___ __  _ __ ___  / _(_) | ___
# \ \/ / '_ \| '__/ _ \| |_| | |/ _ \
#  >  <| |_) | | | (_) |  _| | |  __/
# /_/\_\ .__/|_|  \___/|_| |_|_|\___|
#      |_|
#
# This file runs when a DM logs you into a grapical session
# and is sourced by xinitrc

# Apply .Xresources (not asynchronosly as following commands need it)
[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources ] &&
	xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources

# Scratchpads
# Wait 0.5 seconds before calling fastfetch to ensure that the fastfetch won't
# wrap its information. This would happen if it prints before the terminal size
# is set to the correct value.
$TERMINAL -n dropdown-general -e $SHELL -c "sleep 1;fastfetch;$SHELL" &
$TERMINAL -n dropdown-math -f xft:Hack:pixelsize=24 -e qalc -c &
$TERMINAL -n ncmpcpp -e $SHELL -c "ncmpcpp" &

# Set background (using custom script)
setbg

# Blue light filter
redshift &

# Statusbar
# dwmblocks &

# Opacity effects
picom -b

# Hide mouse cursor when typing
xbanish &

# Flash the focused window
flashfocus &

# Notifications
dunst &

# Set numlock
xdotool key --clearmodifiers Num_Lock &

# Setup extended monitor
setup-monitors &

# Set keyboard settings
setup-keyboard

# setup lock screen (xautolock will also be called by suspend@USER.service)
xautolock -detectsleep -resetsaver \
    -locker "xsecurelock" -time 10 -notify 5 \
    -notifier "/usr/lib/xsecurelock/until_nonidle /usr/lib/xsecurelock/dimmer" \
    -killer "systemctl suspend" -killtime 50 &

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd &

# Syncthing (for syncing folders with computers/smartphones)
syncthing -no-browser -no-restart -logflags=0 &

# Apply cursor theme (workaround for bug in awesome wm)
xsetroot -cursor_name left_ptr &

# Setup keyring
dbus-update-activation-environment --all
gnome-keyring-daemon --start --components=secrets

# Start music visualizer after short delay to ensure that wallpaper is
# already set
# sh -c 'sleep 10 && glava --desktop'

# Startup applications
firefox &

