#!/bin/sh
while read file
do
	case "$1" in
	"o")
        mpv --script-opts=autoload-disabled=yes "$(echo $file | sed 's/\/.video-thumbnail-cache//' | sed 's/.jpg/.mp4/' | sed 's/.png/.mp4/')" 1>/dev/null ||
        mpv --script-opts=autoload-disabled=yes "$(echo $file | sed 's/\/.video-thumbnail-cache//' | sed 's/.jpg/.m4v/' | sed 's/.png/.m4v/')" 1>/dev/null ||
        mpv --script-opts=autoload-disabled=yes "$(echo $file | sed 's/\/.video-thumbnail-cache//' | sed 's/.jpg/.webm/' | sed 's/.png/.webm/')" 1>/dev/null ||
		mpv --script-opts=autoload-disabled=yes "$file" 1>/dev/null & ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | tr -d '\n' | xclip -selection clipboard \
            && notify-send -t 3000 "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard \
            && notify-send -t 3000 "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] \
            && rm "$file" \
            && notify-send -t 3000 "$file deleted." ;;
	"g")	ifinstalled gimp && setsid -f gimp "$file" ;;
	"i")	notify-send -t 10000 "File information" "$(mediainfo "$file")" ;;
	esac
done
