#!/bin/sh
#
#

if [ "$1" = "period-changed" ]; then
    old_period="$2"
    new_period="$3"

    case "$new_period" in
        daytime)
            icon="~/.config/redshift/hooks/daytime.png"
            ;;
        night)
            icon="~/.config/redshift/hooks/night.png"
            ;;
        transition)
            icon="~/.config/redshift/hooks/transition.png"
            ;;
        none)
            icon="~/.config/redshift/hooks/lightbulb.png"
            ;;
        *)
            icon="~/.config/redshift/hooks/lightbulb.png"
            ;;
    esac

    notify-send \
        --icon="$icon" \
        -- "Redshift" "Period changed to $3"
fi
