#!/bin/sh
#
# This file gets sourced by config files of shells like
#   - bashrc
#   - zshrc

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Sudo not required for some system commands
for x in mount umount pacman ; do
	alias $x="sudo $x"
done

# Color
alias ls='ls --color=auto --group-directories-first --human-readable --literal'
alias ll='ls -l'
alias la='ls -la'

alias grep='grep --color=auto'
alias diff='diff --color=auto'

# Verbosity and other common settings
alias \
	cd='cd -P' \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Abbreviations for common commands
alias \
	ka="killall" \
	g="git" \
	yt="youtube-viewer" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura"

# Other
alias lf='lf-ueberzug'
alias yt='youtube-dl --add-metadata --ignore-errors'	# Download video
alias yta='yt -x'										# Download only audio
