#!/bin/sh
#                   __ _ _
#  _ __  _ __ ___  / _(_) | ___
# | '_ \| '__/ _ \| |_| | |/ _ \
# | |_) | | | (_) |  _| | |  __/
# | .__/|_|  \___/|_| |_|_|\___|
# |_|
#
# Runs on login
# Environmental variables are set here
#
# Create a symlink to
#   - '~/.zprofile' (zsh)
#   - '~/.bash_profile' (bash)
# for it to work.

# Call .bashrc (aliases and functions)
# [[ -f ~/.bashrc ]] && . ~/.bashrc

# --------------------------------------------------
# Environment variables
# --------------------------------------------------

# Command prompt
#PS1="\e[1;36m\u@\h\e[m:\e[1;33m\W\e[m\$ "

# Paths
export PATH="$PATH:${$(find $HOME/.local/bin -type d -printf %p:)%%:}"

# Default programs
export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export COLORTERM="truecolor"
export PAGER="less"
export MANPAGER="nvim +Man!"
export WM="awesome"
export DIFFPROG="nvimdiff"  # For pacdiff

# XDG directories
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# Directories for custom scripts
export ZETTELKASTEN_DIR="$HOME/zettelkasten"
export SCRNSHOT_DIR="$HOME/pictures/screenshots"
export LOCKSCREEN_DIR="$XDG_DATA_HOME/lockscreen/"
export BLOG_DIR="$HOME/data/_user/programming/html/projects/blog/public/"

# ~/ cleanup
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export GDBHISTFILE="$XDG_DATA_HOME/gdb/history"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GOPATH="$XDG_DATA_HOME/go"
export SSB_HOME="$XDG_DATA_HOME/zoom"
export LEIN_HOME="$XDG_DATA_HOME/lein"
export DIALOGRC="$XDG_CONFIG_HOME/dialog/dialogrc"
export R_ENVIRON_USER="$XDG_CONFIG_HOME/r/.Renviron"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export RANDFILE="$XDG_CACHE_HOME/openssl/rnd"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"

# custom variables called in ~/.config/shell/.aliasrc
export FREEPLANE_DATA_HOME="$XDG_DATA_HOME/freeplane"
export MVN_SETTINGS_HOME="$XDG_CONFIG_HOME/maven/settings.xml"
export VSCODE_DATA_HOME="$XDG_DATA_HOME/vscode"

# Might cause errors for VSCodium / VSCode (original path: ~/.vscode-oss)
export VSCODE_PORTABLE="$VSCODE_DATA_HOME"

# This line will break some DMs (e.g. LightDM, SLiM)
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# Xsecurelock (screenlock) settings
export XSECURELOCK_AUTH_BACKGROUND_COLOR="rgb:28/28/28"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="rgb:dd/dd/dd"
export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_LIST_VIDEOS_COMMAND="find ${LOCKSCREEN_DIR} -xtype f"
export XSECURELOCK_IMAGE_DURATION_SECONDS=3600
export XSECURELOCK_SHOW_HOSTNAME=0
export XSECURELOCK_SHOW_USERNAME=0
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=1
export XSECURELOCK_DIM_TIME_MS=1000
export XSECURELOCK_WAIT_TIME_MS=5000

# Use Java 17
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"

# Difftastic settings
export DFT_TAB_WIDTH=4

# --------------------------------------------------
# Window manager
# --------------------------------------------------
if [ "$(tty)" = "/dev/tty1" ]; then
    # Start graphical server
    exec startx
fi

# Set theme for tty
if [ "$TERM" = "linux" ]; then
    printf "\e]P0232323" #black
    printf "\e]P82B2B2B" #darkgrey
    printf "\e]P1D75F5F" #darkred
    printf "\e]P9E33636" #red
    printf "\e]P287AF5F" #darkgreen
    printf "\e]PA98E34D" #green
    printf "\e]P3D7AF87" #brown
    printf "\e]PBFFD75F" #yellow
    printf "\e]P48787AF" #darkblue
    printf "\e]PC7373C9" #blue
    printf "\e]P5BD53A5" #darkmagenta
    printf "\e]PDD633B2" #magenta
    printf "\e]P65FAFAF" #darkcyan
    printf "\e]PE44C9C9" #cyan
    printf "\e]P7E5E5E5" #lightgrey
    printf "\e]PFFFFFFF" #white
    clear #for background artifacting
fi
