#!/bin/sh
#                   __ _ _
#  _ __  _ __ ___  / _(_) | ___
# | '_ \| '__/ _ \| |_| | |/ _ \
# | |_) | | | (_) |  _| | |  __/
# | .__/|_|  \___/|_| |_|_|\___|
# |_|
#
# Runs on login
# Environmental variables are set here
#
# Create a symlink to
#   - '~/.zprofile' (zsh)
#   - '~/.bash_profile' (bash)
# for it to work.

# Call .bashrc (aliases and functions)
# [[ -f ~/.bashrc ]] && . ~/.bashrc

# --------------------------------------------------
# Environment variables
# --------------------------------------------------

# Command prompt
#PS1="\e[1;36m\u@\h\e[m:\e[1;33m\W\e[m\$ "

# Paths
export PATH="$PATH:${$(find $HOME/.local/bin -type d -printf %p:)%%:}"
export CDPATH=".:$HOME/cd-shortcuts"

# Default programs
export EDITOR="nvim"
export VISUAL="vscodium"
export TERMINAL="st"
export BROWSER="firefox"
export COLORTERM="truecolor"
export PAGER="less"
export WM="i3"


# XDG directories
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# Zettelkasten
export ZETTELKASTEN_DIR="$HOME/zettelkasten"

# ~/ cleanup
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GOPATH="$XDG_DATA_HOME/go"

# Might cause errors for VSCodium / VSCode (original path: ~/.vscode-oss)
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

# This line will break some DMs (e.g. LightDM, SLiM)
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

# Xsecurelock (screenlock) settings
export XSECURELOCK_NO_COMPOSITE=1
export XSECURELOCK_SAVER=saver_mpv
export XSECURELOCK_LIST_VIDEOS_COMMAND="find ${XDG_DATA_HOME:-$HOME/.local/share/}/lockscreen/ -xtype f"
export XSECURELOCK_IMAGE_DURATION_SECONDS=3600
export XSECURELOCK_SHOW_HOSTNAME=0
export XSECURELOCK_SHOW_USERNAME=0

# Source icons list for file manager (lf)
LF_ICONS=$(sed ~/.config/diricons \
            -e '/^[ \t]*#/d'       \
            -e '/^[ \t]*$/d'       \
            -e 's/[ \t]\+/=/g'     \
            -e 's/$/ /')
LF_ICONS=${LF_ICONS//$'\n'/:}
export LF_ICONS

# --------------------------------------------------
# Window manager
# --------------------------------------------------
# Start graphical server if i3 is not already running
if [ "$(tty)" = "/dev/tty1" ]; then
	pgrep -x i3 || exec startx "$XINITRC"
fi

